# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\erser\Desktop\pythonn 3.8\YT_VIDEO_DOWNLOADER\downloaderForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Downloader(object):
    def setupUi(self, Downloader):
        Downloader.setObjectName("Downloader")
        Downloader.resize(945, 159)
        Downloader.setAnimated(True)
        Downloader.setDocumentMode(False)
        Downloader.setTabShape(QtWidgets.QTabWidget.Rounded)
        Downloader.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(Downloader)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 110, 901, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.url = QtWidgets.QLineEdit(self.centralwidget)
        self.url.setGeometry(QtCore.QRect(100, 20, 791, 22))
        self.url.setObjectName("url")
        self.urlText = QtWidgets.QLabel(self.centralwidget)
        self.urlText.setGeometry(QtCore.QRect(10, 10, 91, 41))
        self.urlText.setObjectName("urlText")
        self.resultText = QtWidgets.QLabel(self.centralwidget)
        self.resultText.setGeometry(QtCore.QRect(10, 90, 291, 16))
        self.resultText.setText("")
        self.resultText.setObjectName("resultText")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(800, 50, 93, 28))
        self.pushButton.setObjectName("pushButton")
        Downloader.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Downloader)
        self.statusbar.setObjectName("statusbar")
        Downloader.setStatusBar(self.statusbar)

        self.retranslateUi(Downloader)
        QtCore.QMetaObject.connectSlotsByName(Downloader)

    def retranslateUi(self, Downloader):
        _translate = QtCore.QCoreApplication.translate
        Downloader.setWindowTitle(_translate("Downloader", "MainWindow"))
        self.urlText.setText(_translate("Downloader", "Enter The Url:"))
        self.pushButton.setText(_translate("Downloader", "Download"))
